### ISSUE TITLE
I will be working on BMI Calcuator project.

### ISSUE THREAD

**Issue by Shrutijn20** [Git-For-Geeks/Javascript-mini-projects#2]

**Comment by Kush-munot** [comment]
@Shrutijn20 Please mention the folder name you want to work on?

**Comment by Shrutijn20** [comment]
BMI calculator

**Comment by Kush-munot** [comment]
@Shrutijn20 Go Ahead with BMI Calculator Project.

Try to make a stellar UI and take inspirations from Dribble and Behance websites.
We wish you best Luck !!
Make your HTML CSS and Javascript files in the BMI calculator Project.

till then Happy Hacking !!
