### ISSUE TITLE
Interactive Rating Component

### ISSUE THREAD

**Issue by jayasingh-14** [Git-For-Geeks/Javascript-mini-projects#31]
Can this project be assigned to me?

**Comment by Kush-munot** [comment]
@jayasingh-14 please elaborate on the project you want to work on?

**Comment by jayasingh-14** [comment]
Just a rating component webpage made in html css and javascript.
![Screenshot_20221027_010104](https://user-images.githubusercontent.com/99128062/198219481-6e14e089-0506-4e0e-b97d-2abc275b6790.png)

**Comment by Kush-munot** [comment]
okay @jayasingh-14 Go ahead and follow proper Steps as mentioned in the ReadME.md !!
